[versions]
agp = "8.6.0"
gson = "2.11.0"
appcompat = "1.7.0"
lombok = "1.18.36"
material = "1.10.0"
mmkv = "2.1.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

